from pathlib import Path

DATA_PATH = Path('data/sounds')

STAGE_WIDTH = 960
STAGE_HEIGHT = 640

ENABLE_LOGGING = True
ENABLE_AUDIO_OUTPUT = True

SOUND_SAMPLE_RATE = 48000
SOUND_RENDER_SIZE = 800

BGM_VOLUME = 0.6
